// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm5o8x0frTB7iLmnnoSOXjeW765YAP6P0',
    appId: '1:76664224122:web:4990d3b05df26fb328fec3',
    messagingSenderId: '76664224122',
    projectId: 'a2chat-ea327',
    authDomain: 'a2chat-ea327.firebaseapp.com',
    storageBucket: 'a2chat-ea327.appspot.com',
    measurementId: 'G-MZ275J9WKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGRwlFxcA2rlzjXm_rklcvxD_b9oCt87Q',
    appId: '1:76664224122:android:69e863aa6db51c6e28fec3',
    messagingSenderId: '76664224122',
    projectId: 'a2chat-ea327',
    storageBucket: 'a2chat-ea327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7K9zddGOBObjUJGmfLVVCMqKkUqMACVk',
    appId: '1:76664224122:ios:1832ebb0013409d828fec3',
    messagingSenderId: '76664224122',
    projectId: 'a2chat-ea327',
    storageBucket: 'a2chat-ea327.appspot.com',
    iosBundleId: 'com.example.a2chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7K9zddGOBObjUJGmfLVVCMqKkUqMACVk',
    appId: '1:76664224122:ios:1832ebb0013409d828fec3',
    messagingSenderId: '76664224122',
    projectId: 'a2chat-ea327',
    storageBucket: 'a2chat-ea327.appspot.com',
    iosBundleId: 'com.example.a2chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm5o8x0frTB7iLmnnoSOXjeW765YAP6P0',
    appId: '1:76664224122:web:e27627722ecea25728fec3',
    messagingSenderId: '76664224122',
    projectId: 'a2chat-ea327',
    authDomain: 'a2chat-ea327.firebaseapp.com',
    storageBucket: 'a2chat-ea327.appspot.com',
    measurementId: 'G-KS5XMGKNCD',
  );

}